//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 31 12:15:19 CEST 2022
//----------------------------------------------------

package zoot.analyse;

/**
 * CUP generated class containing symbol constants.
 */
public class CodesLexicaux {
    /* terminals */
    public static final int RETOURNE = 12;
    public static final int IDF = 29;
    public static final int CSTBOOLEENNE = 31;
    public static final int JUSQUA = 27;
    public static final int EGAL = 8;
    public static final int PARFERMANTE = 11;
    public static final int CSTENTIERE = 30;
    public static final int OU = 17;
    public static final int PLUS = 13;
    public static final int INFERIEUR = 21;
    public static final int ECRIRE = 7;
    public static final int ALORS = 23;
    public static final int DIFFERENT = 20;
    public static final int FONCTIONS = 9;
    public static final int DOUBLEEGAL = 19;
    public static final int VIRGULE = 6;
    public static final int REPETER = 26;
    public static final int NON = 18;
    public static final int MOINS = 15;
    public static final int POINTVIRGULE = 5;
    public static final int SINON = 24;
    public static final int VARIABLES = 4;
    public static final int FINREPETER = 28;
    public static final int ENTIER = 33;
    public static final int EOF = 0;
    public static final int MULT = 14;
    public static final int PAROUVRANTE = 10;
    public static final int SI = 22;
    public static final int ET = 16;
    public static final int error = 1;
    public static final int BOOLEEN = 32;
    public static final int DEBUT = 2;
    public static final int FINSI = 25;
    public static final int FIN = 3;
}

